#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
    procd_open_instance
    # 这里路径填写你 Beverly 上 wstunnel 的绝对路径
    procd_set_param command /usr/bin/wstunnel server ws://0.0.0.0:8443
    # 开启进程死掉后自动拉起
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    # 将日志输出到系统日志，方便用 logread 查看
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
