#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
    procd_open_instance
    # 这里路径填写你 Riviera 上 wstunnel 的绝对路径
    procd_set_param command /root/wstunnel/wstunnel client -L "udp://127.0.0.1:3333:127.0.0.1:8443" ws://beverly.b-gfw.cfd:8443
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
