# -----------------------------------------------------------------------------
# MosDNS v4 配置文件：dat_exec.yaml
# 适用于 MosDNS 5.3.3 及以下版本（v4 DSL）
# 作用：定义所有数据源插件，包括 IP 列表（ip_set）、域名列表（domain_set）、
#      ECS/EDNS 处理器（ecs_handler）以及 TTL 调整插件（sequence）。
# -----------------------------------------------------------------------------

plugins:

  # ┌────────────────────────────────────────────────────────────────────────┐
  # │ 插件：geoip_private                                                  │
  # │ 类型：ip_set                                                         │
  # │ 作用：加载私有网络 IP 列表，用于在分流规则中识别 LAN 内部地址         │
  # │ 文件：/var/mosdns/geoip_private.txt                                  │
  # └────────────────────────────────────────────────────────────────────────┘
  - tag: geoip_private
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_private.txt"

  # ┌────────────────────────────────────────────────────────────────────────┐
  # │ 插件：geoip_cn                                                       │
  # │ 类型：ip_set                                                         │
  # │ 作用：加载中国大陆 IP 列表，用于识别大陆 IP，以便走内网或国内上游      │
  # │ 文件：/var/mosdns/geoip_cn.txt                                       │
  # └────────────────────────────────────────────────────────────────────────┘
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_cn.txt"

  # ┌────────────────────────────────────────────────────────────────────────┐
  # │ 插件：geosite_cn                                                     │
  # │ 类型：domain_set                                                     │
  # │ 作用：加载中国大陆域名列表，用于 qname 匹配大陆域名                    │
  # │ 文件：                                                               │
  # │   - /var/mosdns/geosite_cn.txt    官方 geosite CN 列表                 │
  # │   - /etc/mosdns/rule/whitelist.txt  额外自定义白名单（常见 CDN、内网） │
  # └────────────────────────────────────────────────────────────────────────┘
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"
        - "/etc/mosdns/rule/whitelist.txt"

  # ┌────────────────────────────────────────────────────────────────────────┐
  # │ 插件：geosite_gfw                                                    │
  # │ 类型：domain_set                                                     │
  # │ 作用：加载 GFW 域名列表，用于 qname 匹配需走代理的墙外域名              │
  # │ 文件：                                                               │
  # │   - /var/mosdns/geosite_gfw.txt    官方 GFW 列表                        │
  # │   - /etc/mosdns/rule/greylist.txt   自定义灰名单（如特定网站）         │
  # └────────────────────────────────────────────────────────────────────────┘
  - tag: geosite_gfw
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_gfw.txt"
        - "/etc/mosdns/rule/greylist.txt"

  # ┌────────────────────────────────────────────────────────────────────────┐
  # │ 插件：geosite_location-!cn                                           │
  # │ 类型：domain_set                                                     │
  # │ 作用：加载非中国大陆域名列表，用于识别境外域名（除广告、GFW）          │
  # │ 文件：/var/mosdns/geosite_geolocation-!cn.txt                        │
  # └────────────────────────────────────────────────────────────────────────┘
  - tag: geosite_location-!cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_geolocation-!cn.txt"

  # ┌────────────────────────────────────────────────────────────────────────┐
  # │ 插件：geosite_category-ads-all                                       │
  # │ 类型：domain_set                                                     │
  # │ 作用：加载广告与拦截域名列表，用于在规则中直接拒绝或返回 NXDOMAIN      │
  # │ 文件：/var/mosdns/geosite_category-ads-all.txt                       │
  # └────────────────────────────────────────────────────────────────────────┘
  - tag: geosite_category-ads-all
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_category-ads-all.txt"

  # ┌────────────────────────────────────────────────────────────────────────┐
  # │ 插件：no_ecs                                                         │
  # │ 类型：ecs_handler                                                    │
  # │ 作用：处理客户端带来的 EDNS Client Subnet (ECS)，本插件关闭所有 ECS   │
  # │ 参数说明：                                                            │
  # │   forward: false   # 不转发下游请求的 ECS                              │
  # │   preset: ""       # 不发送任何预设的 ECS                              │
  # │   send: false      # 完全不在上游请求中发送 ECS                        │
  # │   mask4: 24        # IPv4 ECS 掩码                                      │
  # │   mask6: 48        # IPv6 ECS 掩码                                      │
  # └────────────────────────────────────────────────────────────────────────┘
  - tag: no_ecs
    type: ecs_handler
    args:
      forward: false
      preset: ""
      send: false
      mask4: 24
      mask6: 48

  # ┌────────────────────────────────────────────────────────────────────────┐
  # │ 插件：ecs_cn                                                         │
  # │ 类型：ecs_handler                                                    │
  # │ 作用：为中国大陆查询附加预设 ECS 但不发送，用于调试或特定流程           │
  # │ 参数同 no_ecs，仅 preset 设置为大陆 ECS IP (114.217.98.237)          │
  # └────────────────────────────────────────────────────────────────────────┘
  - tag: ecs_cn
    type: ecs_handler
    args:
      forward: false
      preset: 114.217.98.237
      send: false
      mask4: 24
      mask6: 48

  # ┌────────────────────────────────────────────────────────────────────────┐
  # │ 插件：ttl_1m                                                        │
  # │ 类型：sequence                                                      │
  # │ 作用：将最终响应的 TTL 强制设置为 60 秒，用于控制缓存时长             │
  # │ args: exec: ttl 60                                                  │
  # └────────────────────────────────────────────────────────────────────────┘
  - tag: ttl_1m
    type: sequence
    args:
      - exec: "ttl 60"

  # ┌────────────────────────────────────────────────────────────────────────┐
  # │ 插件：ttl_5m                                                        │
  # │ 类型：sequence                                                      │
  # │ 作用：将最终响应的 TTL 强制设置为 300 秒（5 分钟），用于缓存策略       │
  # └────────────────────────────────────────────────────────────────────────┘
  - tag: ttl_5m
    type: sequence
    args:
      - exec: "ttl 300"

  # ┌────────────────────────────────────────────────────────────────────────┐
  # │ 插件：ttl_1h                                                        │
  # │ 类型：sequence                                                      │
  # │ 作用：将最终响应的 TTL 强制设置为 3600 秒（1 小时），用于长缓存策略   │
  # └────────────────────────────────────────────────────────────────────────┘
  - tag: ttl_1h
    type: sequence
    args:
      - exec: "ttl 3600"
