# --------------------------------------------------------------------------------
# MosDNS v4 配置示例：dns.yaml
# 适用于 MosDNS 5.3.3 及以下版本（v4 DSL）
# 作用：定义上游 DNS 转发插件（forward），并将它们通过 tag 标识，供 config_custom.yaml 中引用
# --------------------------------------------------------------------------------

plugins:
  # ┌─────────────────────────────────────────────────────────┐
  # │ 插件：ADH_CN                                          │
  # │ 作用：将匹配到的请求转发到国内 AdGuard Home 实例（TCP） │
  # └─────────────────────────────────────────────────────────┘
  - tag: ADH_CN                      # 插件名称，调用时使用 $ADH_CN
    type: forward                   # 插件类型：forward，用于转发到上游 DNS
    args:                           # forward 插件的参数
      concurrent: 1                 # 同时并发连接数，1 表示对每个查询使用一个连接，可按需求调整
      upstreams:                     # 上游服务器列表，可配置多条以增加冗余
        - addr: "tcp://172.20.0.1:54"  
          # addr: 指定协议+地址+端口
          #  - tcp:// 表示使用 TCP 协议发送 DNS 请求
          #  - 172.20.0.1:54 是 ADH_CN 在宿主机或容器外暴露的 TCP 端口

  # ┌─────────────────────────────────────────────────────────┐
  # │ 插件：ADH_GFW                                         │
  # │ 作用：将匹配到的请求转发到国外 AdGuard Home 实例（TCP）  │
  # └─────────────────────────────────────────────────────────┘
  - tag: ADH_GFW                     # 插件名称，调用时使用 $ADH_GFW
    type: forward                   # 插件类型同上：forward
    args:
      concurrent: 1                 # 并发连接数，可根据网络质量酌情增加
      upstreams:
        - addr: "tcp://172.20.0.1:55"
          # addr: 使用 TCP 协议，目标为国外 AdGuard Home 容器
          # 172.20.0.1:55 是该服务在宿主机或其他虚拟机上监听的 TCP 端口

# --------------------------------------------------------------------------------
# 注意事项：
# 1. 每个 upstreams 项目必须是一个 map（即包含 addr 字段），不能直接写字符串。
# 2. 若需要更细粒度控制，可在每个 upstream 下添加：
#      dial_addr: "<IP>"        # 指定实际拨号的目标地址（可省略，默认从 addr 中解析）
#      timeout: "<duration>"    # 覆盖默认超时时间（例如 "2s"）
#      retries: <number>        # 覆盖默认重试次数
# 3. v4 DSL 不支持顶层 retries/timeout/edns_client_subnet 等字段，如需自定义请在插件 args 中单独设置。
# 4. 本文件与 config_custom.yaml、dat_exec.yaml 共同构成完整配置，三者缺一不可。
