services:
  mosdns:
    image: irinesistiana/mosdns:latest
    container_name: mosdns
    ports:
      - "53:5333/udp"
      - "53:5333/tcp"
    volumes:
      - ./config:/etc/mosdns
      - ./rules-dat:/var/mosdns
      - ./mosdns.log:/var/log/mosdns.log
    entrypoint: |
      /bin/sh -c "\
      : > /var/log/mosdns.log && \
      exec mosdns start -c /etc/mosdns/config_custom.yaml\
      "
    restart: unless-stopped
